import { DegreeLevel, IntakePeriod } from '@prisma/client';
import type { UniversitySeed } from './destinations-data';

/** Additional study destinations beyond USA, UK, Australia */
export const GLOBAL_COUNTRY_DATA = [
  {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    description:
      'World-class universities, affordable tuition, multicultural cities, and clear post-graduation work permit pathways for international students.',
    tuitionRange: 'CAD 18,000 – 45,000/year',
    livingCost: 'CAD 12,000 – 18,000/year',
    visaRequirements: 'Study Permit. IELTS 6.0–6.5 or equivalent English proof.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.JANUARY, IntakePeriod.MAY],
    graduateOpportunities: 'PGWP allows up to 3 years of post-study work; strong PR pathway.',
  },
  {
    code: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    description:
      'Low or no tuition at public universities, Europe\'s engineering powerhouse, and strong industry links for STEM graduates.',
    tuitionRange: '€0 – €20,000/year (public unis often free)',
    livingCost: '€10,000 – €12,000/year',
    visaRequirements: 'Student visa + blocked account. IELTS/TOEFL or German proficiency depending on program.',
    intakePeriods: [IntakePeriod.OCTOBER, IntakePeriod.APRIL],
    graduateOpportunities: '18-month job-seeker visa after graduation; EU Blue Card pathway.',
  },
  {
    code: 'FR',
    name: 'France',
    flag: '🇫🇷',
    description:
      'Prestigious grandes écoles and universities with affordable public tuition and growing English-taught Masters programs.',
    tuitionRange: '€2,800 – €15,000/year',
    livingCost: '€10,000 – €14,000/year',
    visaRequirements: 'Student visa (VLS-TS). IELTS 6.0+ for English programs.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.JANUARY],
    graduateOpportunities: 'APS visa allows 12 months to seek employment after graduation.',
  },
  {
    code: 'IE',
    name: 'Ireland',
    flag: '🇮🇪',
    description:
      'EU tech hub with 1-year Masters, English-medium education, and strong graduate visa options for IT and pharma sectors.',
    tuitionRange: '€12,000 – €35,000/year',
    livingCost: '€10,000 – €15,000/year',
    visaRequirements: 'Study visa. IELTS 6.5 typically required.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.JANUARY],
    graduateOpportunities: 'Third Level Graduate Scheme — up to 2 years post-study work.',
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    flag: '🇳🇿',
    description:
      'Safe, high-quality education with practical learning, stunning campuses, and straightforward post-study work visas.',
    tuitionRange: 'NZD 26,000 – 45,000/year',
    livingCost: 'NZD 15,000 – 20,000/year',
    visaRequirements: 'Student Visa. IELTS 6.0–6.5 typically required.',
    intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.JULY],
    graduateOpportunities: 'Post-study work visa up to 3 years depending on qualification level.',
  },
  {
    code: 'SG',
    name: 'Singapore',
    flag: '🇸🇬',
    description:
      'Asia\'s education hub with globally ranked universities, strong business schools, and proximity to Indian students.',
    tuitionRange: 'SGD 20,000 – 45,000/year',
    livingCost: 'SGD 12,000 – 18,000/year',
    visaRequirements: 'Student Pass (IPA). IELTS/TOEFL for English-medium programs.',
    intakePeriods: [IntakePeriod.AUGUST, IntakePeriod.JANUARY],
    graduateOpportunities: 'Employment Pass pathway for graduates with job offers.',
  },
  {
    code: 'NL',
    name: 'Netherlands',
    flag: '🇳🇱',
    description:
      '2,000+ English-taught programs, innovative teaching, and orientation year visa for international graduates.',
    tuitionRange: '€8,000 – €20,000/year',
    livingCost: '€10,000 – €14,000/year',
    visaRequirements: 'MVV + residence permit. IELTS 6.0–6.5 for English programs.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.FEBRUARY],
    graduateOpportunities: 'Orientation Year permit — 1 year to find work after graduation.',
  },
  {
    code: 'IT',
    name: 'Italy',
    flag: '🇮🇹',
    description:
      'Affordable EU education, rich cultural heritage, and growing English-taught Masters in design, engineering, and business.',
    tuitionRange: '€1,000 – €15,000/year',
    livingCost: '€8,000 – €12,000/year',
    visaRequirements: 'Study visa (D-type). IELTS or proof of English-medium prior degree.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.FEBRUARY],
    graduateOpportunities: '12-month permesso di soggiorno for job search after graduation.',
  },
  {
    code: 'CH',
    name: 'Switzerland',
    flag: '🇨🇭',
    description:
      'Home to ETH Zurich and EPFL — world-leading STEM, hospitality, and finance programs with strong industry placement.',
    tuitionRange: 'CHF 1,000 – 8,000/year (public) + living',
    livingCost: 'CHF 18,000 – 28,000/year',
    visaRequirements: 'National D visa. IELTS/TOEFL and strong academic profile.',
    intakePeriods: [IntakePeriod.SEPTEMBER],
    graduateOpportunities: '6-month job search permit for graduates; strong pharma & banking sectors.',
  },
  {
    code: 'AE',
    name: 'UAE',
    flag: '🇦🇪',
    description:
      'Dubai and Abu Dhabi host branch campuses of global universities with tax-free earning potential and modern infrastructure.',
    tuitionRange: 'AED 40,000 – 120,000/year',
    livingCost: 'AED 30,000 – 50,000/year',
    visaRequirements: 'Student residence visa sponsored by university. IELTS 5.5–6.5.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.JANUARY],
    graduateOpportunities: 'Employment visa sponsorship through UAE-based employers.',
  },
  {
    code: 'JP',
    name: 'Japan',
    flag: '🇯🇵',
    description:
      'Cutting-edge technology, MEXT scholarships, and increasing English-taught programs at top national universities.',
    tuitionRange: '¥535,800 – ¥1,500,000/year',
    livingCost: '¥1,000,000 – ¥1,500,000/year',
    visaRequirements: 'Student visa (COE required). JLPT or IELTS depending on program language.',
    intakePeriods: [IntakePeriod.APRIL, IntakePeriod.SEPTEMBER],
    graduateOpportunities: 'Designated Activities visa for job hunting up to 1 year post-graduation.',
  },
  {
    code: 'KR',
    name: 'South Korea',
    flag: '🇰🇷',
    description:
      'Rising destination for engineering, K-culture studies, and STEM with KGSP scholarships and English-taught programs.',
    tuitionRange: 'KRW 4M – 12M/year',
    livingCost: 'KRW 8M – 12M/year',
    visaRequirements: 'D-2 Student visa. IELTS/TOEFL for English programs; TOPIK for Korean programs.',
    intakePeriods: [IntakePeriod.MARCH, IntakePeriod.SEPTEMBER],
    graduateOpportunities: 'D-10 job-seeker visa for graduates seeking employment.',
  },
  {
    code: 'MY',
    name: 'Malaysia',
    flag: '🇲🇾',
    description:
      'Affordable Asian destination with UK/Australian branch campuses, multicultural environment, and easy visa processing.',
    tuitionRange: 'MYR 20,000 – 60,000/year',
    livingCost: 'MYR 15,000 – 25,000/year',
    visaRequirements: 'Student Pass. IELTS 5.5–6.0 for most programs.',
    intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.SEPTEMBER],
    graduateOpportunities: 'Employment Pass for graduates with qualifying job offers.',
  },
  {
    code: 'SE',
    name: 'Sweden',
    flag: '🇸🇪',
    description:
      'Innovation-driven education, sustainability focus, and English-taught Masters at globally respected universities.',
    tuitionRange: 'SEK 80,000 – 295,000/year',
    livingCost: 'SEK 90,000 – 120,000/year',
    visaRequirements: 'Residence permit for studies. IELTS 6.5 for English programs.',
    intakePeriods: [IntakePeriod.AUGUST, IntakePeriod.JANUARY],
    graduateOpportunities: '6-month residence permit extension to seek employment.',
  },
  {
    code: 'ES',
    name: 'Spain',
    flag: '🇪🇸',
    description:
      'Affordable EU tuition, vibrant student cities, and growing English-taught business and engineering programs.',
    tuitionRange: '€1,000 – €18,000/year',
    livingCost: '€8,000 – €12,000/year',
    visaRequirements: 'Student visa (Type D). IELTS for English programs; Spanish for others.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.FEBRUARY],
    graduateOpportunities: '12-month post-study residence authorization for job search.',
  },
  {
    code: 'FI',
    name: 'Finland',
    flag: '🇫🇮',
    description:
      'World-leading education system, English-taught programs, and high quality of life with strong tech and design sectors.',
    tuitionRange: '€8,000 – €18,000/year',
    livingCost: '€9,000 – €13,000/year',
    visaRequirements: 'Residence permit for studies. IELTS 6.0–6.5 for English programs.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.JANUARY],
    graduateOpportunities: '2-year residence permit extension to find work after graduation.',
  },
] as const;

export const GLOBAL_UNIVERSITIES: UniversitySeed[] = [
  {
    name: 'University of Toronto',
    slug: 'university-of-toronto',
    countryCode: 'CA',
    worldRanking: 21,
    tuitionMin: 45000,
    tuitionMax: 65000,
    acceptanceRate: 43,
    description: 'Canada\'s top university with world-class research across engineering, business, and health sciences.',
    website: 'https://www.utoronto.ca',
    popularPrograms: ['Computer Science', 'Engineering', 'Business', 'Data Science'],
    courses: [{
      name: 'Master of Engineering in Electrical & Computer',
      slug: 'uoft-meng-ece',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '1 year',
      tuition: 58000,
      currency: 'CAD',
      intakePeriods: [IntakePeriod.SEPTEMBER],
      eligibility: 'Bachelor\'s in ECE with 75%+. IELTS 7.0.',
      description: 'Professional graduate engineering degree at U of T Faculty of Applied Science.',
      sourceUrl: 'https://www.utoronto.ca',
    }],
    scholarships: [],
  },
  {
    name: 'University of British Columbia',
    slug: 'university-of-british-columbia',
    countryCode: 'CA',
    worldRanking: 34,
    tuitionMin: 40000,
    tuitionMax: 55000,
    acceptanceRate: 52,
    description: 'Leading Canadian research university on the Pacific coast with strong co-op programs.',
    website: 'https://www.ubc.ca',
    popularPrograms: ['Computer Science', 'Forestry', 'Business', 'Engineering'],
    courses: [{
      name: 'Master of Data Science',
      slug: 'ubc-mds',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '10 months',
      tuition: 52000,
      currency: 'CAD',
      intakePeriods: [IntakePeriod.SEPTEMBER],
      eligibility: 'Quantitative bachelor\'s degree. IELTS 7.0.',
      description: 'Intensive data science professional masters at UBC Vancouver.',
      sourceUrl: 'https://www.ubc.ca',
    }],
    scholarships: [],
  },
  {
    name: 'Technical University of Munich',
    slug: 'technical-university-munich',
    countryCode: 'DE',
    worldRanking: 37,
    tuitionMin: 0,
    tuitionMax: 6000,
    acceptanceRate: 48,
    description: 'Germany\'s #1 technical university — engineering, informatics, and natural sciences excellence.',
    website: 'https://www.tum.de',
    popularPrograms: ['Informatics', 'Mechanical Engineering', 'Physics', 'Management'],
    courses: [{
      name: 'MSc Informatics',
      slug: 'tum-msc-informatics',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '2 years',
      tuition: 0,
      currency: 'EUR',
      intakePeriods: [IntakePeriod.OCTOBER, IntakePeriod.APRIL],
      eligibility: 'CS bachelor\'s with strong GPA. IELTS 6.5 or German C1.',
      description: 'Research-oriented informatics masters at TUM School of Computation, Information and Technology.',
      sourceUrl: 'https://www.tum.de',
    }],
    scholarships: [],
  },
  {
    name: 'Trinity College Dublin',
    slug: 'trinity-college-dublin',
    countryCode: 'IE',
    worldRanking: 81,
    tuitionMin: 20000,
    tuitionMax: 35000,
    acceptanceRate: 55,
    description: 'Ireland\'s oldest and most prestigious university in the heart of Dublin\'s tech corridor.',
    website: 'https://www.tcd.ie',
    popularPrograms: ['Computer Science', 'Pharmaceutical Sciences', 'Business', 'Law'],
    courses: [{
      name: 'MSc Computer Science',
      slug: 'tcd-msc-cs',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '1 year',
      tuition: 28000,
      currency: 'EUR',
      intakePeriods: [IntakePeriod.SEPTEMBER],
      eligibility: 'CS or related bachelor\'s. IELTS 6.5.',
      description: 'Full-time taught masters in computer science at Trinity College Dublin.',
      sourceUrl: 'https://www.tcd.ie',
    }],
    scholarships: [],
  },
  {
    name: 'National University of Singapore',
    slug: 'national-university-singapore',
    countryCode: 'SG',
    worldRanking: 8,
    tuitionMin: 35000,
    tuitionMax: 55000,
    acceptanceRate: 25,
    description: 'Asia\'s leading global university with top-ranked engineering, computing, and business schools.',
    website: 'https://www.nus.edu.sg',
    popularPrograms: ['Computer Science', 'Business Analytics', 'Engineering', 'Public Policy'],
    courses: [{
      name: 'MSc Business Analytics',
      slug: 'nus-msba',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '1 year',
      tuition: 48000,
      currency: 'SGD',
      intakePeriods: [IntakePeriod.AUGUST],
      eligibility: 'Bachelor\'s with quantitative background. IELTS 7.0.',
      description: 'Business analytics masters at NUS Business School.',
      sourceUrl: 'https://www.nus.edu.sg',
    }],
    scholarships: [],
  },
  {
    name: 'Delft University of Technology',
    slug: 'delft-university-technology',
    countryCode: 'NL',
    worldRanking: 47,
    tuitionMin: 15000,
    tuitionMax: 20000,
    acceptanceRate: 60,
    description: 'Netherlands\' top technical university renowned for engineering, architecture, and aerospace.',
    website: 'https://www.tudelft.nl',
    popularPrograms: ['Aerospace Engineering', 'Computer Science', 'Architecture', 'Robotics'],
    courses: [{
      name: 'MSc Computer Science',
      slug: 'tudelft-msc-cs',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '2 years',
      tuition: 18500,
      currency: 'EUR',
      intakePeriods: [IntakePeriod.SEPTEMBER],
      eligibility: 'CS bachelor\'s. IELTS 6.5.',
      description: 'English-taught computer science masters at TU Delft.',
      sourceUrl: 'https://www.tudelft.nl',
    }],
    scholarships: [],
  },
  {
    name: 'University of Auckland',
    slug: 'university-of-auckland',
    countryCode: 'NZ',
    worldRanking: 68,
    tuitionMin: 32000,
    tuitionMax: 48000,
    acceptanceRate: 58,
    description: 'New Zealand\'s highest-ranked university with strong research and industry connections.',
    website: 'https://www.auckland.ac.nz',
    popularPrograms: ['Engineering', 'Computer Science', 'Business', 'Health Sciences'],
    courses: [{
      name: 'Master of Engineering Studies',
      slug: 'auckland-meng-studies',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '1 year',
      tuition: 42000,
      currency: 'NZD',
      intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.JULY],
      eligibility: 'Engineering bachelor\'s. IELTS 6.5.',
      description: 'Taught engineering masters at University of Auckland Faculty of Engineering.',
      sourceUrl: 'https://www.auckland.ac.nz',
    }],
    scholarships: [],
  },
  {
    name: 'Sorbonne University',
    slug: 'sorbonne-university',
    countryCode: 'FR',
    worldRanking: 59,
    tuitionMin: 3000,
    tuitionMax: 12000,
    acceptanceRate: 50,
    description: 'Historic French research university with growing English-taught international programs.',
    website: 'https://www.sorbonne-universite.fr',
    popularPrograms: ['Engineering', 'Physics', 'Medicine', 'Literature'],
    courses: [{
      name: 'MSc Computer Science',
      slug: 'sorbonne-msc-cs',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '2 years',
      tuition: 3770,
      currency: 'EUR',
      intakePeriods: [IntakePeriod.SEPTEMBER],
      eligibility: 'CS bachelor\'s. IELTS 6.0 or French B2.',
      description: 'Computer science masters at Sorbonne Faculty of Science and Engineering.',
      sourceUrl: 'https://www.sorbonne-universite.fr',
    }],
    scholarships: [],
  },
  {
    name: 'ETH Zurich',
    slug: 'eth-zurich',
    countryCode: 'CH',
    worldRanking: 7,
    tuitionMin: 1500,
    tuitionMax: 3000,
    acceptanceRate: 27,
    description: 'World\'s leading science and technology university — Albert Einstein\'s alma mater.',
    website: 'https://ethz.ch',
    popularPrograms: ['Computer Science', 'Robotics', 'Data Science', 'Architecture'],
    courses: [{
      name: 'MSc Computer Science',
      slug: 'eth-msc-cs',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '2 years',
      tuition: 1800,
      currency: 'CHF',
      intakePeriods: [IntakePeriod.SEPTEMBER],
      eligibility: 'Outstanding CS bachelor\'s. IELTS 7.0 or German C1.',
      description: 'Research-intensive computer science masters at ETH Zurich.',
      sourceUrl: 'https://ethz.ch',
    }],
    scholarships: [],
  },
  {
    name: 'University of Dubai',
    slug: 'university-of-dubai',
    countryCode: 'AE',
    worldRanking: 0,
    tuitionMin: 35000,
    tuitionMax: 80000,
    acceptanceRate: 70,
    description: 'Leading UAE institution offering accredited business, IT, and engineering programs in Dubai.',
    website: 'https://www.ud.ac.ae',
    popularPrograms: ['MBA', 'Information Technology', 'Business', 'Law'],
    courses: [{
      name: 'MBA',
      slug: 'ud-mba',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '1 year',
      tuition: 65000,
      currency: 'AED',
      intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.JANUARY],
      eligibility: 'Bachelor\'s + 2 years work experience. IELTS 6.0.',
      description: 'Accelerated MBA program at University of Dubai.',
      sourceUrl: 'https://www.ud.ac.ae',
    }],
    scholarships: [],
  },
];
