import { DegreeLevel, IntakePeriod } from '@prisma/client';
import { GLOBAL_COUNTRY_DATA, GLOBAL_UNIVERSITIES } from './destinations-global';

/** All active study destination country codes */
export const FOCUS_COUNTRY_CODES = [
  'US', 'GB', 'AU', 'CA', 'DE', 'FR', 'IE', 'NZ', 'SG', 'NL',
  'IT', 'CH', 'AE', 'JP', 'KR', 'MY', 'SE', 'ES', 'FI',
] as const;

export const COUNTRY_DATA = [
  {
    code: 'US',
    name: 'United States',
    flag: '🇺🇸',
    description:
      'Home to the world\'s top-ranked universities with exceptional research, innovation, and OPT work opportunities for international graduates.',
    tuitionRange: '$25,000 – $65,000/year',
    livingCost: '$12,000 – $22,000/year',
    visaRequirements: 'F-1 Student Visa. IELTS 6.5+ or TOEFL 90+ typically required.',
    intakePeriods: [IntakePeriod.FALL, IntakePeriod.SPRING],
    graduateOpportunities: 'OPT allows 12 months (36 months for STEM) of post-study work.',
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    flag: '🇬🇧',
    description:
      'Prestigious universities with shorter degree durations — 3-year UG and 1-year Masters — plus Graduate Route work visa.',
    tuitionRange: '£18,000 – £45,000/year',
    livingCost: '£10,000 – £16,000/year',
    visaRequirements: 'Student Route visa. IELTS 6.0–7.0 depending on institution.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.JANUARY],
    graduateOpportunities: 'Graduate Route visa allows 2 years (3 years for PhD) post-study work.',
  },
  {
    code: 'AU',
    name: 'Australia',
    flag: '🇦🇺',
    description:
      'High-quality education in a multicultural environment with strong post-study work rights and world-leading research universities.',
    tuitionRange: 'AUD 32,000 – 55,000/year',
    livingCost: 'AUD 20,000 – 27,000/year',
    visaRequirements: 'Student Visa (Subclass 500). IELTS 6.0–6.5 typically required.',
    intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.JULY],
    graduateOpportunities: 'Temporary Graduate visa (485) allows 2–4 years post-study work.',
  },
  ...GLOBAL_COUNTRY_DATA,
] as const;

export interface CourseSeed {
  name: string;
  slug: string;
  degreeLevel: DegreeLevel;
  duration: string;
  tuition: number;
  currency: string;
  intakePeriods: IntakePeriod[];
  eligibility: string;
  description: string;
  sourceUrl: string;
}

export interface ScholarshipSeed {
  id: string;
  name: string;
  awardAmount: number;
  currency: string;
  deadline: string;
  eligibility: string;
  requirements: string;
  sourceUrl: string;
  courseSlug?: string;
}

export interface UniversitySeed {
  name: string;
  slug: string;
  countryCode: string;
  worldRanking: number;
  tuitionMin: number;
  tuitionMax: number;
  acceptanceRate: number;
  description: string;
  website: string;
  popularPrograms: string[];
  courses: CourseSeed[];
  scholarships: ScholarshipSeed[];
}

export const UNIVERSITIES: UniversitySeed[] = [
  // ─── USA ───────────────────────────────────────────────────────────────────
  {
    name: 'Massachusetts Institute of Technology',
    slug: 'massachusetts-institute-of-technology',
    countryCode: 'US',
    worldRanking: 1,
    tuitionMin: 57590,
    tuitionMax: 61990,
    acceptanceRate: 4,
    description: 'World-leading institution in science, technology, engineering, and mathematics.',
    website: 'https://www.mit.edu',
    popularPrograms: ['Computer Science', 'Electrical Engineering', 'Business Analytics'],
    courses: [
      {
        name: 'BS in Computer Science and Engineering',
        slug: 'mit-bs-computer-science-engineering',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '4 years',
        tuition: 61990,
        currency: 'USD',
        intakePeriods: [IntakePeriod.FALL],
        eligibility: 'Strong high school STEM record. SAT/ACT optional. English proficiency required.',
        description: 'Undergraduate program covering algorithms, AI, systems, and software engineering.',
        sourceUrl: 'https://www.mit.edu/admissions-aid/undergraduate-admissions',
      },
      {
        name: 'MS in Electrical Engineering and Computer Science',
        slug: 'mit-ms-eecs',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 61990,
        currency: 'USD',
        intakePeriods: [IntakePeriod.FALL],
        eligibility: 'Bachelor\'s in EE/CS. GRE not required. Strong academic record.',
        description: 'Graduate research program in EECS with AI, robotics, and systems focus.',
        sourceUrl: 'https://www.eecs.mit.edu/academics-admissions/graduate-program',
      },
    ],
    scholarships: [
      {
        id: 'sch-mit-intl-excellence',
        name: 'MIT International Excellence Award',
        awardAmount: 25000,
        currency: 'USD',
        deadline: '2026-12-15',
        eligibility: 'International applicants with outstanding academic merit.',
        requirements: 'Admission application, transcripts, and financial documentation.',
        sourceUrl: 'https://sfs.mit.edu/undergraduate-students/types-of-aid/scholarships',
      },
    ],
  },
  {
    name: 'Stanford University',
    slug: 'stanford-university',
    countryCode: 'US',
    worldRanking: 3,
    tuitionMin: 56169,
    tuitionMax: 65730,
    acceptanceRate: 4,
    description: 'Premier research university in Silicon Valley with strong entrepreneurship culture.',
    website: 'https://www.stanford.edu',
    popularPrograms: ['Computer Science', 'MBA', 'Data Science', 'Engineering'],
    courses: [
      {
        name: 'BS in Computer Science',
        slug: 'stanford-bs-computer-science',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '4 years',
        tuition: 65730,
        currency: 'USD',
        intakePeriods: [IntakePeriod.FALL],
        eligibility: 'Exceptional academic record. English proficiency. Holistic admissions review.',
        description: 'Core CS theory, systems, AI, and human-computer interaction.',
        sourceUrl: 'https://cs.stanford.edu/degrees/undergrad',
      },
      {
        name: 'MS in Computer Science',
        slug: 'stanford-ms-computer-science',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '1.5–2 years',
        tuition: 56169,
        currency: 'USD',
        intakePeriods: [IntakePeriod.FALL],
        eligibility: 'Bachelor\'s in CS or related field. Strong GPA and research background.',
        description: 'Specializations in AI, systems, theory, and HCI.',
        sourceUrl: 'https://cs.stanford.edu/degrees/masters',
      },
    ],
    scholarships: [
      {
        id: 'sch-stanford-knight-hennessy',
        name: 'Knight-Hennessy Scholars Program',
        awardAmount: 75000,
        currency: 'USD',
        deadline: '2026-10-11',
        eligibility: 'Graduate applicants demonstrating leadership and civic commitment.',
        requirements: 'Graduate school application plus Knight-Hennessy separate application.',
        sourceUrl: 'https://knight-hennessy.stanford.edu',
      },
    ],
  },
  {
    name: 'Harvard University',
    slug: 'harvard-university',
    countryCode: 'US',
    worldRanking: 4,
    tuitionMin: 54269,
    tuitionMax: 73440,
    acceptanceRate: 3,
    description: 'Ivy League institution with world-renowned faculties across arts, sciences, and professional schools.',
    website: 'https://www.harvard.edu',
    popularPrograms: ['Economics', 'Computer Science', 'MBA', 'Public Health'],
    courses: [
      {
        name: 'AB in Computer Science',
        slug: 'harvard-ab-computer-science',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '4 years',
        tuition: 59076,
        currency: 'USD',
        intakePeriods: [IntakePeriod.FALL],
        eligibility: 'Outstanding secondary school record. English proficiency required.',
        description: 'Harvard College undergraduate degree in computer science.',
        sourceUrl: 'https://college.harvard.edu/admissions',
      },
      {
        name: 'MBA — Harvard Business School',
        slug: 'harvard-mba',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 73440,
        currency: 'USD',
        intakePeriods: [IntakePeriod.FALL],
        eligibility: 'Bachelor\'s degree. 2+ years work experience. GMAT/GRE required.',
        description: 'Full-time MBA program at Harvard Business School.',
        sourceUrl: 'https://www.hbs.edu/mba/admissions',
      },
    ],
    scholarships: [
      {
        id: 'sch-harvard-intl',
        name: 'Harvard Financial Aid — International Students',
        awardAmount: 50000,
        currency: 'USD',
        deadline: '2026-02-01',
        eligibility: 'Admitted international students demonstrating financial need.',
        requirements: 'CSS Profile and institutional financial aid application.',
        sourceUrl: 'https://college.harvard.edu/financial-aid',
      },
    ],
  },
  {
    name: 'University of California, Berkeley',
    slug: 'university-of-california-berkeley',
    countryCode: 'US',
    worldRanking: 12,
    tuitionMin: 46892,
    tuitionMax: 52890,
    acceptanceRate: 11,
    description: 'Top public research university known for engineering, business, and social sciences.',
    website: 'https://www.berkeley.edu',
    popularPrograms: ['EECS', 'Business', 'Data Science', 'Environmental Science'],
    courses: [
      {
        name: 'BS in Electrical Engineering & Computer Sciences',
        slug: 'ucb-bs-eecs',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '4 years',
        tuition: 52890,
        currency: 'USD',
        intakePeriods: [IntakePeriod.FALL],
        eligibility: 'Strong STEM grades. English proficiency. UC application required.',
        description: 'EECS undergraduate program — one of the top CS programs globally.',
        sourceUrl: 'https://eecs.berkeley.edu/academics/undergraduate',
      },
      {
        name: 'Master of Engineering in EECS',
        slug: 'ucb-meng-eecs',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '1 year',
        tuition: 46892,
        currency: 'USD',
        intakePeriods: [IntakePeriod.FALL],
        eligibility: 'Bachelor\'s in engineering or CS. Minimum 3.0 GPA.',
        description: 'Industry-focused one-year professional masters in EECS.',
        sourceUrl: 'https://eecs.berkeley.edu/academics/graduate/industry-programs',
      },
    ],
    scholarships: [
      {
        id: 'sch-berkeley-regents',
        name: 'UC Berkeley Regents\' and Chancellor\'s Scholarship',
        awardAmount: 15000,
        currency: 'USD',
        deadline: '2026-12-01',
        eligibility: 'Outstanding incoming undergraduates including international students.',
        requirements: 'Automatic consideration with UC application.',
        sourceUrl: 'https://financialaid.berkeley.edu/types-of-aid-at-berkeley/scholarships',
      },
    ],
  },
  {
    name: 'Columbia University',
    slug: 'columbia-university',
    countryCode: 'US',
    worldRanking: 18,
    tuitionMin: 54500,
    tuitionMax: 69728,
    acceptanceRate: 4,
    description: 'Ivy League university in New York City with strong programs in journalism, business, and engineering.',
    website: 'https://www.columbia.edu',
    popularPrograms: ['Computer Science', 'Journalism', 'International Affairs', 'MBA'],
    courses: [
      {
        name: 'BS in Computer Science',
        slug: 'columbia-bs-computer-science',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '4 years',
        tuition: 69728,
        currency: 'USD',
        intakePeriods: [IntakePeriod.FALL],
        eligibility: 'Competitive academic record. English proficiency required.',
        description: 'Columbia Engineering undergraduate CS program in NYC.',
        sourceUrl: 'https://www.engineering.columbia.edu/admissions/undergraduate',
      },
      {
        name: 'MS in Data Science',
        slug: 'columbia-ms-data-science',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '1.5 years',
        tuition: 69728,
        currency: 'USD',
        intakePeriods: [IntakePeriod.FALL, IntakePeriod.SPRING],
        eligibility: 'Quantitative bachelor\'s degree. Programming and statistics background.',
        description: 'Interdisciplinary data science masters from Columbia\'s Data Science Institute.',
        sourceUrl: 'https://datascience.columbia.edu/education/programs/m-s-in-data-science',
      },
    ],
    scholarships: [
      {
        id: 'sch-columbia-intl',
        name: 'Columbia International Student Grant',
        awardAmount: 20000,
        currency: 'USD',
        deadline: '2026-11-15',
        eligibility: 'International students with demonstrated financial need.',
        requirements: 'CSS Profile and admission application.',
        sourceUrl: 'https://sfs.columbia.edu/content/international-students',
      },
    ],
  },

  // ─── UK ────────────────────────────────────────────────────────────────────
  {
    name: 'University of Oxford',
    slug: 'university-of-oxford',
    countryCode: 'GB',
    worldRanking: 2,
    tuitionMin: 28950,
    tuitionMax: 48630,
    acceptanceRate: 17,
    description: 'Oldest university in the English-speaking world with collegiate tutorial system.',
    website: 'https://www.ox.ac.uk',
    popularPrograms: ['PPE', 'Law', 'Medicine', 'Computer Science', 'MBA'],
    courses: [
      {
        name: 'BA in Computer Science',
        slug: 'oxford-ba-computer-science',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '3 years',
        tuition: 39120,
        currency: 'GBP',
        intakePeriods: [IntakePeriod.OCTOBER],
        eligibility: 'A-levels or equivalent. Strong mathematics. Admissions test may apply.',
        description: 'Three-year undergraduate computer science at Oxford.',
        sourceUrl: 'https://www.ox.ac.uk/admissions/undergraduate',
      },
      {
        name: 'MSc in Computer Science',
        slug: 'oxford-msc-computer-science',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '1 year',
        tuition: 36900,
        currency: 'GBP',
        intakePeriods: [IntakePeriod.OCTOBER],
        eligibility: 'First-class or strong upper second bachelor\'s in CS or related field.',
        description: 'One-year taught masters in advanced computer science.',
        sourceUrl: 'https://www.ox.ac.uk/admissions/graduate',
      },
      {
        name: 'MBA — Saïd Business School',
        slug: 'oxford-mba',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '1 year',
        tuition: 78640,
        currency: 'GBP',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'Bachelor\'s degree. 2+ years work experience. GMAT/GRE required.',
        description: 'One-year intensive MBA at Oxford Saïd Business School.',
        sourceUrl: 'https://www.sbs.ox.ac.uk/programmes/degrees/mba',
      },
    ],
    scholarships: [
      {
        id: 'sch-oxford-clarendon',
        name: 'Clarendon Fund Scholarship',
        awardAmount: 18000,
        currency: 'GBP',
        deadline: '2026-01-20',
        eligibility: 'Outstanding graduate applicants across all subjects.',
        requirements: 'Automatic consideration with graduate course application.',
        sourceUrl: 'https://www.ox.ac.uk/clarendon',
        courseSlug: 'oxford-msc-computer-science',
      },
      {
        id: 'sch-chevening',
        name: 'Chevening Scholarship (UK Government)',
        awardAmount: 35000,
        currency: 'GBP',
        deadline: '2026-11-05',
        eligibility: 'Future leaders with 2+ years work experience from Chevening-eligible countries.',
        requirements: 'Separate Chevening application plus UK university offer.',
        sourceUrl: 'https://www.chevening.org',
      },
    ],
  },
  {
    name: 'University of Cambridge',
    slug: 'university-of-cambridge',
    countryCode: 'GB',
    worldRanking: 5,
    tuitionMin: 25000,
    tuitionMax: 72000,
    acceptanceRate: 18,
    description: 'World-renowned collegiate university with excellence in sciences, engineering, and humanities.',
    website: 'https://www.cam.ac.uk',
    popularPrograms: ['Natural Sciences', 'Engineering', 'Economics', 'Computer Science'],
    courses: [
      {
        name: 'BA in Computer Science',
        slug: 'cambridge-ba-computer-science',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '3 years',
        tuition: 39162,
        currency: 'GBP',
        intakePeriods: [IntakePeriod.OCTOBER],
        eligibility: 'A-levels or equivalent with strong mathematics. Admissions assessment.',
        description: 'Cambridge undergraduate computer science tripos.',
        sourceUrl: 'https://www.undergraduate.study.cam.ac.uk',
      },
      {
        name: 'MPhil in Advanced Computer Science',
        slug: 'cambridge-mphil-computer-science',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '1 year',
        tuition: 42000,
        currency: 'GBP',
        intakePeriods: [IntakePeriod.OCTOBER],
        eligibility: 'First-class bachelor\'s in CS. Research proposal may be required.',
        description: 'Advanced taught masters with research dissertation component.',
        sourceUrl: 'https://www.postgraduate.study.cam.ac.uk',
      },
    ],
    scholarships: [
      {
        id: 'sch-cambridge-gates',
        name: 'Gates Cambridge Scholarship',
        awardAmount: 40000,
        currency: 'GBP',
        deadline: '2026-10-11',
        eligibility: 'Outstanding international graduate applicants outside the UK.',
        requirements: 'Graduate admission application plus Gates Cambridge application.',
        sourceUrl: 'https://www.gatescambridge.org',
      },
    ],
  },
  {
    name: 'Imperial College London',
    slug: 'imperial-college-london',
    countryCode: 'GB',
    worldRanking: 6,
    tuitionMin: 33000,
    tuitionMax: 45000,
    acceptanceRate: 14,
    description: 'STEM-focused university in London, ranked among the world\'s best for engineering and medicine.',
    website: 'https://www.imperial.ac.uk',
    popularPrograms: ['Engineering', 'Computing', 'Medicine', 'Business'],
    courses: [
      {
        name: 'BEng in Computing',
        slug: 'imperial-beng-computing',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '3 years',
        tuition: 40940,
        currency: 'GBP',
        intakePeriods: [IntakePeriod.OCTOBER],
        eligibility: 'A-levels AAA including Mathematics. English proficiency.',
        description: 'Computing undergraduate degree at Imperial\'s Department of Computing.',
        sourceUrl: 'https://www.imperial.ac.uk/study/undergraduate',
      },
      {
        name: 'MSc in Computing (AI & ML)',
        slug: 'imperial-msc-computing-ai',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '1 year',
        tuition: 43250,
        currency: 'GBP',
        intakePeriods: [IntakePeriod.OCTOBER],
        eligibility: 'First-class bachelor\'s in computing or related quantitative field.',
        description: 'Specialist masters in artificial intelligence and machine learning.',
        sourceUrl: 'https://www.imperial.ac.uk/study/postgraduate',
      },
    ],
    scholarships: [
      {
        id: 'sch-imperial-president',
        name: 'Imperial President\'s PhD Scholarship',
        awardAmount: 25000,
        currency: 'GBP',
        deadline: '2026-01-15',
        eligibility: 'Outstanding PhD applicants across all faculties.',
        requirements: 'PhD programme application. Covers fees and stipend.',
        sourceUrl: 'https://www.imperial.ac.uk/study/fees-and-funding',
      },
    ],
  },
  {
    name: 'University College London',
    slug: 'university-college-london',
    countryCode: 'GB',
    worldRanking: 9,
    tuitionMin: 28000,
    tuitionMax: 42000,
    acceptanceRate: 16,
    description: 'London\'s global university with strengths in medicine, law, architecture, and data science.',
    website: 'https://www.ucl.ac.uk',
    popularPrograms: ['Data Science', 'Architecture', 'Medicine', 'Economics'],
    courses: [
      {
        name: 'BSc in Computer Science',
        slug: 'ucl-bsc-computer-science',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '3 years',
        tuition: 37500,
        currency: 'GBP',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'A-levels A*AA including Mathematics. English proficiency.',
        description: 'UCL Computer Science undergraduate programme.',
        sourceUrl: 'https://www.ucl.ac.uk/prospective-students/undergraduate',
      },
      {
        name: 'MSc in Data Science and Machine Learning',
        slug: 'ucl-msc-data-science',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '1 year',
        tuition: 36500,
        currency: 'GBP',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'Upper second bachelor\'s in quantitative discipline.',
        description: 'Taught masters combining statistics, ML, and big data systems.',
        sourceUrl: 'https://www.ucl.ac.uk/prospective-students/graduate',
      },
    ],
    scholarships: [
      {
        id: 'sch-ucl-global',
        name: 'UCL Global Undergraduate Scholarship',
        awardAmount: 15000,
        currency: 'GBP',
        deadline: '2026-05-31',
        eligibility: 'International undergraduate applicants with financial need.',
        requirements: 'UCAS application and scholarship application form.',
        sourceUrl: 'https://www.ucl.ac.uk/scholarships',
        courseSlug: 'ucl-bsc-computer-science',
      },
    ],
  },
  {
    name: 'University of Manchester',
    slug: 'university-of-manchester',
    countryCode: 'GB',
    worldRanking: 32,
    tuitionMin: 22000,
    tuitionMax: 32000,
    acceptanceRate: 45,
    description: 'Russell Group university and the largest single-site university in the UK.',
    website: 'https://www.manchester.ac.uk',
    popularPrograms: ['Engineering', 'Business', 'Computer Science', 'Pharmacy'],
    courses: [
      {
        name: 'BSc in Computer Science',
        slug: 'manchester-bsc-computer-science',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '3 years',
        tuition: 30000,
        currency: 'GBP',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'A-levels or equivalent with mathematics. IELTS 6.5.',
        description: 'Computer science undergraduate at the School of Computer Science.',
        sourceUrl: 'https://www.manchester.ac.uk/study/undergraduate',
      },
      {
        name: 'MSc in Advanced Computer Science',
        slug: 'manchester-msc-computer-science',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '1 year',
        tuition: 32000,
        currency: 'GBP',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'Upper second bachelor\'s in CS or related field.',
        description: 'Advanced CS masters with AI, software engineering, and data analytics options.',
        sourceUrl: 'https://www.manchester.ac.uk/study/masters',
      },
    ],
    scholarships: [
      {
        id: 'sch-manchester-equity',
        name: 'Manchester International Equity Scholarship',
        awardAmount: 10000,
        currency: 'GBP',
        deadline: '2026-06-30',
        eligibility: 'Self-funded international postgraduate taught students.',
        requirements: 'Offer holder application via scholarship portal.',
        sourceUrl: 'https://www.manchester.ac.uk/study/fees-and-funding',
      },
    ],
  },

  // ─── Australia ─────────────────────────────────────────────────────────────
  {
    name: 'University of Melbourne',
    slug: 'university-of-melbourne',
    countryCode: 'AU',
    worldRanking: 13,
    tuitionMin: 35000,
    tuitionMax: 52000,
    acceptanceRate: 70,
    description: 'Australia\'s leading university with the Melbourne Model and strong research output.',
    website: 'https://www.unimelb.edu.au',
    popularPrograms: ['Commerce', 'Engineering', 'Medicine', 'Data Science'],
    courses: [
      {
        name: 'Bachelor of Science — Computing and Software Systems',
        slug: 'melbourne-bsc-computing',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '3 years',
        tuition: 48576,
        currency: 'AUD',
        intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.JULY],
        eligibility: 'ATAR 85+ or equivalent. Mathematics prerequisite. IELTS 6.5.',
        description: 'Computing major within the Bachelor of Science at Melbourne.',
        sourceUrl: 'https://study.unimelb.edu.au/find/courses/undergraduate',
      },
      {
        name: 'Master of Information Technology',
        slug: 'melbourne-mit',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 52000,
        currency: 'AUD',
        intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.JULY],
        eligibility: 'Bachelor\'s degree. Prior computing experience preferred.',
        description: 'Professional IT masters with software, AI, and cybersecurity streams.',
        sourceUrl: 'https://study.unimelb.edu.au/find/courses/graduate',
      },
    ],
    scholarships: [
      {
        id: 'sch-melbourne-intl-ug',
        name: 'Melbourne International Undergraduate Scholarship',
        awardAmount: 10000,
        currency: 'AUD',
        deadline: '2026-11-30',
        eligibility: 'High-achieving international undergraduate applicants.',
        requirements: 'Automatic consideration with course application.',
        sourceUrl: 'https://scholarships.unimelb.edu.au',
        courseSlug: 'melbourne-bsc-computing',
      },
    ],
  },
  {
    name: 'University of Sydney',
    slug: 'university-of-sydney',
    countryCode: 'AU',
    worldRanking: 19,
    tuitionMin: 42000,
    tuitionMax: 55000,
    acceptanceRate: 65,
    description: 'Australia\'s first university with a stunning campus and globally ranked professional schools.',
    website: 'https://www.sydney.edu.au',
    popularPrograms: ['Business', 'Engineering', 'Medicine', 'Computer Science'],
    courses: [
      {
        name: 'Bachelor of Advanced Computing',
        slug: 'sydney-bachelor-advanced-computing',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '4 years',
        tuition: 54800,
        currency: 'AUD',
        intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.JULY],
        eligibility: 'ATAR 90+ or equivalent. Mathematics Extension 1. IELTS 6.5.',
        description: 'Advanced computing degree with AI, data science, and software engineering majors.',
        sourceUrl: 'https://www.sydney.edu.au/study/undergraduate',
      },
      {
        name: 'Master of Professional Engineering (Software)',
        slug: 'sydney-mpe-software',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '3 years',
        tuition: 52000,
        currency: 'AUD',
        intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.JULY],
        eligibility: 'Engineering or IT bachelor\'s. Accredited pathway to professional engineer status.',
        description: 'Professional engineering masters accredited by Engineers Australia.',
        sourceUrl: 'https://www.sydney.edu.au/study/postgraduate',
      },
    ],
    scholarships: [
      {
        id: 'sch-sydney-vc-intl',
        name: 'Sydney Vice-Chancellor International Scholarships',
        awardAmount: 40000,
        currency: 'AUD',
        deadline: '2026-12-31',
        eligibility: 'High-achieving international students commencing coursework degrees.',
        requirements: 'Automatic consideration with admission application.',
        sourceUrl: 'https://www.sydney.edu.au/scholarships',
      },
    ],
  },
  {
    name: 'UNSW Sydney',
    slug: 'unsw-sydney',
    countryCode: 'AU',
    worldRanking: 19,
    tuitionMin: 42000,
    tuitionMax: 54000,
    acceptanceRate: 60,
    description: 'Leading Australian university known for engineering, business, and quantum computing research.',
    website: 'https://www.unsw.edu.au',
    popularPrograms: ['Engineering', 'Computer Science', 'Business', 'Law'],
    courses: [
      {
        name: 'Bachelor of Computer Science',
        slug: 'unsw-bachelor-computer-science',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '3 years',
        tuition: 50850,
        currency: 'AUD',
        intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.SEPTEMBER],
        eligibility: 'ATAR 85+ or equivalent. Mathematics. IELTS 6.5 overall.',
        description: 'Computer science undergraduate at UNSW School of Computer Science and Engineering.',
        sourceUrl: 'https://www.unsw.edu.au/study/undergraduate',
      },
      {
        name: 'Master of Information Technology',
        slug: 'unsw-master-information-technology',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 54000,
        currency: 'AUD',
        intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.SEPTEMBER],
        eligibility: 'Recognised bachelor\'s degree. Computing background recommended.',
        description: 'MIT program with specialisations in AI, cybersecurity, and database systems.',
        sourceUrl: 'https://www.unsw.edu.au/study/postgraduate',
      },
    ],
    scholarships: [
      {
        id: 'sch-unsw-intl',
        name: 'UNSW International Scientia Scholarship',
        awardAmount: 20000,
        currency: 'AUD',
        deadline: '2026-11-01',
        eligibility: 'High-achieving international students across all faculties.',
        requirements: 'Admission application. Merit-based automatic assessment.',
        sourceUrl: 'https://www.unsw.edu.au/study/fees-and-financial-support',
      },
    ],
  },
  {
    name: 'Monash University',
    slug: 'monash-university',
    countryCode: 'AU',
    worldRanking: 37,
    tuitionMin: 38000,
    tuitionMax: 50000,
    acceptanceRate: 55,
    description: 'Australia\'s largest university with campuses in Melbourne and international partnerships.',
    website: 'https://www.monash.edu',
    popularPrograms: ['Pharmacy', 'Engineering', 'Business', 'IT'],
    courses: [
      {
        name: 'Bachelor of Computer Science',
        slug: 'monash-bachelor-computer-science',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '3 years',
        tuition: 46400,
        currency: 'AUD',
        intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.JULY],
        eligibility: 'ATAR 80+ or equivalent. Mathematics. IELTS 6.5.',
        description: 'CS undergraduate with AI, data science, and software engineering majors.',
        sourceUrl: 'https://www.monash.edu/study/courses/find-a-course',
      },
      {
        name: 'Master of Data Science',
        slug: 'monash-master-data-science',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 50000,
        currency: 'AUD',
        intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.JULY],
        eligibility: 'Quantitative bachelor\'s degree with statistics or programming.',
        description: 'Data science masters covering ML, big data, and visualisation.',
        sourceUrl: 'https://www.monash.edu/study/courses/find-a-course',
      },
    ],
    scholarships: [
      {
        id: 'sch-monash-intl-leadership',
        name: 'Monash International Leadership Scholarship',
        awardAmount: 10000,
        currency: 'AUD',
        deadline: '2026-10-31',
        eligibility: 'International students demonstrating academic excellence and leadership.',
        requirements: 'Separate scholarship application after receiving offer.',
        sourceUrl: 'https://www.monash.edu/study/fees-scholarships/scholarships',
      },
    ],
  },
  {
    name: 'Australian National University',
    slug: 'australian-national-university',
    countryCode: 'AU',
    worldRanking: 34,
    tuitionMin: 40000,
    tuitionMax: 52000,
    acceptanceRate: 50,
    description: 'National research university in Canberra with strong government and policy connections.',
    website: 'https://www.anu.edu.au',
    popularPrograms: ['International Relations', 'Computer Science', 'Economics', 'Law'],
    courses: [
      {
        name: 'Bachelor of Computing',
        slug: 'anu-bachelor-computing',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '3 years',
        tuition: 48552,
        currency: 'AUD',
        intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.JULY],
        eligibility: 'ATAR 85+ or equivalent. Mathematics Methods. IELTS 6.5.',
        description: 'Computing undergraduate at ANU College of Engineering, Computing and Cybernetics.',
        sourceUrl: 'https://www.anu.edu.au/study/undergraduate',
      },
      {
        name: 'Master of Computing',
        slug: 'anu-master-computing',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 52000,
        currency: 'AUD',
        intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.JULY],
        eligibility: 'Bachelor\'s in computing or related field with minimum 60% average.',
        description: 'Advanced computing masters with AI, systems, and HCI specialisations.',
        sourceUrl: 'https://www.anu.edu.au/study/postgraduate',
      },
    ],
    scholarships: [
      {
        id: 'sch-anu-coe',
        name: 'ANU College of Engineering & Computer Science International Scholarship',
        awardAmount: 15000,
        currency: 'AUD',
        deadline: '2026-11-15',
        eligibility: 'International students in CECS postgraduate coursework programs.',
        requirements: 'Offer holder. Merit-based selection.',
        sourceUrl: 'https://www.anu.edu.au/study/scholarships',
        courseSlug: 'anu-master-computing',
      },
    ],
  },
  ...GLOBAL_UNIVERSITIES,
];

/** Country-level scholarships not tied to a single university */
export const COUNTRY_SCHOLARSHIPS = [
  {
    id: 'sch-fulbright',
    countryCode: 'US' as const,
    name: 'Fulbright Foreign Student Program',
    awardAmount: 50000,
    currency: 'USD',
    deadline: '2026-05-15',
    eligibility: 'Graduate students and young professionals from participating countries.',
    requirements: 'Separate Fulbright application. University admission required.',
    sourceUrl: 'https://foreign.fulbrightonline.org',
  },
  {
    id: 'sch-australia-awards',
    countryCode: 'AU' as const,
    name: 'Australia Awards Scholarships',
    awardAmount: 60000,
    currency: 'AUD',
    deadline: '2026-04-30',
    eligibility: 'Citizens of participating developing countries pursuing study in Australia.',
    requirements: 'Online application via Australia Awards portal.',
    sourceUrl: 'https://www.dfat.gov.au/australia-awards',
  },
  {
    id: 'sch-commonwealth',
    countryCode: 'GB' as const,
    name: 'Commonwealth Scholarship (UK)',
    awardAmount: 30000,
    currency: 'GBP',
    deadline: '2026-12-15',
    eligibility: 'Citizens of Commonwealth developing countries for masters study.',
    requirements: 'Application via national nominating agency.',
    sourceUrl: 'https://cscuk.fcdo.gov.uk',
  },
];
