import { DegreeLevel, IntakePeriod } from '@prisma/client';
import type { UniversitySeed } from './destinations-data';

/** Additional study destinations beyond USA, UK, Australia */
export const GLOBAL_COUNTRY_DATA = [
  {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    description:
      'World-class universities, affordable tuition, multicultural cities, and clear post-graduation work permit pathways for international students.',
    tuitionRange: 'CAD 18,000 – 45,000/year',
    livingCost: 'CAD 12,000 – 18,000/year',
    visaRequirements: 'Study Permit. IELTS 6.0–6.5 or equivalent English proof.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.JANUARY, IntakePeriod.MAY],
    graduateOpportunities: 'PGWP allows up to 3 years of post-study work; strong PR pathway.',
  },
  {
    code: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    description:
      'Low or no tuition at public universities, Europe\'s engineering powerhouse, and strong industry links for STEM graduates.',
    tuitionRange: '€0 – €20,000/year (public unis often free)',
    livingCost: '€10,000 – €12,000/year',
    visaRequirements: 'Student visa + blocked account. IELTS/TOEFL or German proficiency depending on program.',
    intakePeriods: [IntakePeriod.OCTOBER, IntakePeriod.APRIL],
    graduateOpportunities: '18-month job-seeker visa after graduation; EU Blue Card pathway.',
  },
  {
    code: 'FR',
    name: 'France',
    flag: '🇫🇷',
    description:
      'Prestigious grandes écoles and universities with affordable public tuition and growing English-taught Masters programs.',
    tuitionRange: '€2,800 – €15,000/year',
    livingCost: '€10,000 – €14,000/year',
    visaRequirements: 'Student visa (VLS-TS). IELTS 6.0+ for English programs.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.JANUARY],
    graduateOpportunities: 'APS visa allows 12 months to seek employment after graduation.',
  },
  {
    code: 'IE',
    name: 'Ireland',
    flag: '🇮🇪',
    description:
      'EU tech hub with 1-year Masters, English-medium education, and strong graduate visa options for IT and pharma sectors.',
    tuitionRange: '€12,000 – €35,000/year',
    livingCost: '€10,000 – €15,000/year',
    visaRequirements: 'Study visa. IELTS 6.5 typically required.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.JANUARY],
    graduateOpportunities: 'Third Level Graduate Scheme — up to 2 years post-study work.',
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    flag: '🇳🇿',
    description:
      'Safe, high-quality education with practical learning, stunning campuses, and straightforward post-study work visas.',
    tuitionRange: 'NZD 26,000 – 45,000/year',
    livingCost: 'NZD 15,000 – 20,000/year',
    visaRequirements: 'Student Visa. IELTS 6.0–6.5 typically required.',
    intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.JULY],
    graduateOpportunities: 'Post-study work visa up to 3 years depending on qualification level.',
  },
  {
    code: 'SG',
    name: 'Singapore',
    flag: '🇸🇬',
    description:
      'Asia\'s education hub with globally ranked universities, strong business schools, and proximity to Indian students.',
    tuitionRange: 'SGD 20,000 – 45,000/year',
    livingCost: 'SGD 12,000 – 18,000/year',
    visaRequirements: 'Student Pass (IPA). IELTS/TOEFL for English-medium programs.',
    intakePeriods: [IntakePeriod.AUGUST, IntakePeriod.JANUARY],
    graduateOpportunities: 'Employment Pass pathway for graduates with job offers.',
  },
  {
    code: 'NL',
    name: 'Netherlands',
    flag: '🇳🇱',
    description:
      '2,000+ English-taught programs, innovative teaching, and orientation year visa for international graduates.',
    tuitionRange: '€8,000 – €20,000/year',
    livingCost: '€10,000 – €14,000/year',
    visaRequirements: 'MVV + residence permit. IELTS 6.0–6.5 for English programs.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.FEBRUARY],
    graduateOpportunities: 'Orientation Year permit — 1 year to find work after graduation.',
  },
  {
    code: 'IT',
    name: 'Italy',
    flag: '🇮🇹',
    description:
      'Affordable EU education, rich cultural heritage, and growing English-taught Masters in design, engineering, and business.',
    tuitionRange: '€1,000 – €15,000/year',
    livingCost: '€8,000 – €12,000/year',
    visaRequirements: 'Study visa (D-type). IELTS or proof of English-medium prior degree.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.FEBRUARY],
    graduateOpportunities: '12-month permesso di soggiorno for job search after graduation.',
  },
  {
    code: 'CH',
    name: 'Switzerland',
    flag: '🇨🇭',
    description:
      'Home to ETH Zurich and EPFL — world-leading STEM, hospitality, and finance programs with strong industry placement.',
    tuitionRange: 'CHF 1,000 – 8,000/year (public) + living',
    livingCost: 'CHF 18,000 – 28,000/year',
    visaRequirements: 'National D visa. IELTS/TOEFL and strong academic profile.',
    intakePeriods: [IntakePeriod.SEPTEMBER],
    graduateOpportunities: '6-month job search permit for graduates; strong pharma & banking sectors.',
  },
  {
    code: 'AE',
    name: 'UAE',
    flag: '🇦🇪',
    description:
      'Dubai and Abu Dhabi host branch campuses of global universities with tax-free earning potential and modern infrastructure.',
    tuitionRange: 'AED 40,000 – 120,000/year',
    livingCost: 'AED 30,000 – 50,000/year',
    visaRequirements: 'Student residence visa sponsored by university. IELTS 5.5–6.5.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.JANUARY],
    graduateOpportunities: 'Employment visa sponsorship through UAE-based employers.',
  },
  {
    code: 'JP',
    name: 'Japan',
    flag: '🇯🇵',
    description:
      'Cutting-edge technology, MEXT scholarships, and increasing English-taught programs at top national universities.',
    tuitionRange: '¥535,800 – ¥1,500,000/year',
    livingCost: '¥1,000,000 – ¥1,500,000/year',
    visaRequirements: 'Student visa (COE required). JLPT or IELTS depending on program language.',
    intakePeriods: [IntakePeriod.APRIL, IntakePeriod.SEPTEMBER],
    graduateOpportunities: 'Designated Activities visa for job hunting up to 1 year post-graduation.',
  },
  {
    code: 'KR',
    name: 'South Korea',
    flag: '🇰🇷',
    description:
      'Rising destination for engineering, K-culture studies, and STEM with KGSP scholarships and English-taught programs.',
    tuitionRange: 'KRW 4M – 12M/year',
    livingCost: 'KRW 8M – 12M/year',
    visaRequirements: 'D-2 Student visa. IELTS/TOEFL for English programs; TOPIK for Korean programs.',
    intakePeriods: [IntakePeriod.MARCH, IntakePeriod.SEPTEMBER],
    graduateOpportunities: 'D-10 job-seeker visa for graduates seeking employment.',
  },
  {
    code: 'MY',
    name: 'Malaysia',
    flag: '🇲🇾',
    description:
      'Affordable Asian destination with UK/Australian branch campuses, multicultural environment, and easy visa processing.',
    tuitionRange: 'MYR 20,000 – 60,000/year',
    livingCost: 'MYR 15,000 – 25,000/year',
    visaRequirements: 'Student Pass. IELTS 5.5–6.0 for most programs.',
    intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.SEPTEMBER],
    graduateOpportunities: 'Employment Pass for graduates with qualifying job offers.',
  },
  {
    code: 'SE',
    name: 'Sweden',
    flag: '🇸🇪',
    description:
      'Innovation-driven education, sustainability focus, and English-taught Masters at globally respected universities.',
    tuitionRange: 'SEK 80,000 – 295,000/year',
    livingCost: 'SEK 90,000 – 120,000/year',
    visaRequirements: 'Residence permit for studies. IELTS 6.5 for English programs.',
    intakePeriods: [IntakePeriod.AUGUST, IntakePeriod.JANUARY],
    graduateOpportunities: '6-month residence permit extension to seek employment.',
  },
  {
    code: 'ES',
    name: 'Spain',
    flag: '🇪🇸',
    description:
      'Affordable EU tuition, vibrant student cities, and growing English-taught business and engineering programs.',
    tuitionRange: '€1,000 – €18,000/year',
    livingCost: '€8,000 – €12,000/year',
    visaRequirements: 'Student visa (Type D). IELTS for English programs; Spanish for others.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.FEBRUARY],
    graduateOpportunities: '12-month post-study residence authorization for job search.',
  },
  {
    code: 'FI',
    name: 'Finland',
    flag: '🇫🇮',
    description:
      'World-leading education system, English-taught programs, and high quality of life with strong tech and design sectors.',
    tuitionRange: '€8,000 – €18,000/year',
    livingCost: '€9,000 – €13,000/year',
    visaRequirements: 'Residence permit for studies. IELTS 6.0–6.5 for English programs.',
    intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.JANUARY],
    graduateOpportunities: '2-year residence permit extension to find work after graduation.',
  },
] as const;

export const GLOBAL_UNIVERSITIES: UniversitySeed[] = [
  {
    name: 'University of Toronto',
    slug: 'university-of-toronto',
    countryCode: 'CA',
    worldRanking: 21,
    tuitionMin: 45000,
    tuitionMax: 65000,
    acceptanceRate: 43,
    description: 'Canada\'s top university with world-class research across engineering, business, and health sciences.',
    website: 'https://www.utoronto.ca',
    popularPrograms: ['Computer Science', 'Engineering', 'Business', 'Data Science'],
    courses: [{
      name: 'Master of Engineering in Electrical & Computer',
      slug: 'uoft-meng-ece',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '1 year',
      tuition: 58000,
      currency: 'CAD',
      intakePeriods: [IntakePeriod.SEPTEMBER],
      eligibility: 'Bachelor\'s in ECE with 75%+. IELTS 7.0.',
      description: 'Professional graduate engineering degree at U of T Faculty of Applied Science.',
      sourceUrl: 'https://www.utoronto.ca',
    }],
    scholarships: [],
  },
  {
    name: 'University of British Columbia',
    slug: 'university-of-british-columbia',
    countryCode: 'CA',
    worldRanking: 34,
    tuitionMin: 40000,
    tuitionMax: 55000,
    acceptanceRate: 52,
    description: 'Leading Canadian research university on the Pacific coast with strong co-op programs.',
    website: 'https://www.ubc.ca',
    popularPrograms: ['Computer Science', 'Forestry', 'Business', 'Engineering'],
    courses: [{
      name: 'Master of Data Science',
      slug: 'ubc-mds',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '10 months',
      tuition: 52000,
      currency: 'CAD',
      intakePeriods: [IntakePeriod.SEPTEMBER],
      eligibility: 'Quantitative bachelor\'s degree. IELTS 7.0.',
      description: 'Intensive data science professional masters at UBC Vancouver.',
      sourceUrl: 'https://www.ubc.ca',
    }],
    scholarships: [],
  },
  {
    name: 'Technical University of Munich',
    slug: 'technical-university-munich',
    countryCode: 'DE',
    worldRanking: 37,
    tuitionMin: 0,
    tuitionMax: 6000,
    acceptanceRate: 48,
    description: 'Germany\'s #1 technical university — engineering, informatics, and natural sciences excellence.',
    website: 'https://www.tum.de',
    popularPrograms: ['Informatics', 'Mechanical Engineering', 'Physics', 'Management'],
    courses: [{
      name: 'MSc Informatics',
      slug: 'tum-msc-informatics',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '2 years',
      tuition: 0,
      currency: 'EUR',
      intakePeriods: [IntakePeriod.OCTOBER, IntakePeriod.APRIL],
      eligibility: 'CS bachelor\'s with strong GPA. IELTS 6.5 or German C1.',
      description: 'Research-oriented informatics masters at TUM School of Computation, Information and Technology.',
      sourceUrl: 'https://www.tum.de',
    }],
    scholarships: [],
  },
  {
    name: 'Trinity College Dublin',
    slug: 'trinity-college-dublin',
    countryCode: 'IE',
    worldRanking: 81,
    tuitionMin: 20000,
    tuitionMax: 35000,
    acceptanceRate: 55,
    description: 'Ireland\'s oldest and most prestigious university in the heart of Dublin\'s tech corridor.',
    website: 'https://www.tcd.ie',
    popularPrograms: ['Computer Science', 'Pharmaceutical Sciences', 'Business', 'Law'],
    courses: [{
      name: 'MSc Computer Science',
      slug: 'tcd-msc-cs',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '1 year',
      tuition: 28000,
      currency: 'EUR',
      intakePeriods: [IntakePeriod.SEPTEMBER],
      eligibility: 'CS or related bachelor\'s. IELTS 6.5.',
      description: 'Full-time taught masters in computer science at Trinity College Dublin.',
      sourceUrl: 'https://www.tcd.ie',
    }],
    scholarships: [],
  },
  {
    name: 'National University of Singapore',
    slug: 'national-university-singapore',
    countryCode: 'SG',
    worldRanking: 8,
    tuitionMin: 35000,
    tuitionMax: 55000,
    acceptanceRate: 25,
    description: 'Asia\'s leading global university with top-ranked engineering, computing, and business schools.',
    website: 'https://www.nus.edu.sg',
    popularPrograms: ['Computer Science', 'Business Analytics', 'Engineering', 'Public Policy'],
    courses: [{
      name: 'MSc Business Analytics',
      slug: 'nus-msba',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '1 year',
      tuition: 48000,
      currency: 'SGD',
      intakePeriods: [IntakePeriod.AUGUST],
      eligibility: 'Bachelor\'s with quantitative background. IELTS 7.0.',
      description: 'Business analytics masters at NUS Business School.',
      sourceUrl: 'https://www.nus.edu.sg',
    }],
    scholarships: [],
  },
  {
    name: 'Delft University of Technology',
    slug: 'delft-university-technology',
    countryCode: 'NL',
    worldRanking: 47,
    tuitionMin: 15000,
    tuitionMax: 20000,
    acceptanceRate: 60,
    description: 'Netherlands\' top technical university renowned for engineering, architecture, and aerospace.',
    website: 'https://www.tudelft.nl',
    popularPrograms: ['Aerospace Engineering', 'Computer Science', 'Architecture', 'Robotics'],
    courses: [{
      name: 'MSc Computer Science',
      slug: 'tudelft-msc-cs',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '2 years',
      tuition: 18500,
      currency: 'EUR',
      intakePeriods: [IntakePeriod.SEPTEMBER],
      eligibility: 'CS bachelor\'s. IELTS 6.5.',
      description: 'English-taught computer science masters at TU Delft.',
      sourceUrl: 'https://www.tudelft.nl',
    }],
    scholarships: [],
  },
  {
    name: 'University of Auckland',
    slug: 'university-of-auckland',
    countryCode: 'NZ',
    worldRanking: 68,
    tuitionMin: 32000,
    tuitionMax: 48000,
    acceptanceRate: 58,
    description: 'New Zealand\'s highest-ranked university with strong research and industry connections.',
    website: 'https://www.auckland.ac.nz',
    popularPrograms: ['Engineering', 'Computer Science', 'Business', 'Health Sciences'],
    courses: [{
      name: 'Master of Engineering Studies',
      slug: 'auckland-meng-studies',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '1 year',
      tuition: 42000,
      currency: 'NZD',
      intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.JULY],
      eligibility: 'Engineering bachelor\'s. IELTS 6.5.',
      description: 'Taught engineering masters at University of Auckland Faculty of Engineering.',
      sourceUrl: 'https://www.auckland.ac.nz',
    }],
    scholarships: [],
  },
  {
    name: 'Sorbonne University',
    slug: 'sorbonne-university',
    countryCode: 'FR',
    worldRanking: 59,
    tuitionMin: 3000,
    tuitionMax: 12000,
    acceptanceRate: 50,
    description: 'Historic French research university with growing English-taught international programs.',
    website: 'https://www.sorbonne-universite.fr',
    popularPrograms: ['Engineering', 'Physics', 'Medicine', 'Literature'],
    courses: [{
      name: 'MSc Computer Science',
      slug: 'sorbonne-msc-cs',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '2 years',
      tuition: 3770,
      currency: 'EUR',
      intakePeriods: [IntakePeriod.SEPTEMBER],
      eligibility: 'CS bachelor\'s. IELTS 6.0 or French B2.',
      description: 'Computer science masters at Sorbonne Faculty of Science and Engineering.',
      sourceUrl: 'https://www.sorbonne-universite.fr',
    }],
    scholarships: [],
  },
  {
    name: 'ETH Zurich',
    slug: 'eth-zurich',
    countryCode: 'CH',
    worldRanking: 7,
    tuitionMin: 1500,
    tuitionMax: 3000,
    acceptanceRate: 27,
    description: 'World\'s leading science and technology university — Albert Einstein\'s alma mater.',
    website: 'https://ethz.ch',
    popularPrograms: ['Computer Science', 'Robotics', 'Data Science', 'Architecture'],
    courses: [{
      name: 'MSc Computer Science',
      slug: 'eth-msc-cs',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '2 years',
      tuition: 1800,
      currency: 'CHF',
      intakePeriods: [IntakePeriod.SEPTEMBER],
      eligibility: 'Outstanding CS bachelor\'s. IELTS 7.0 or German C1.',
      description: 'Research-intensive computer science masters at ETH Zurich.',
      sourceUrl: 'https://ethz.ch',
    }],
    scholarships: [],
  },
  {
    name: 'University of Dubai',
    slug: 'university-of-dubai',
    countryCode: 'AE',
    worldRanking: 0,
    tuitionMin: 35000,
    tuitionMax: 80000,
    acceptanceRate: 70,
    description: 'Leading UAE institution offering accredited business, IT, and engineering programs in Dubai.',
    website: 'https://www.ud.ac.ae',
    popularPrograms: ['MBA', 'Information Technology', 'Business', 'Law'],
    courses: [{
      name: 'MBA',
      slug: 'ud-mba',
      degreeLevel: DegreeLevel.MASTERS,
      duration: '1 year',
      tuition: 65000,
      currency: 'AED',
      intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.JANUARY],
      eligibility: 'Bachelor\'s + 2 years work experience. IELTS 6.0.',
      description: 'Accelerated MBA program at University of Dubai.',
      sourceUrl: 'https://www.ud.ac.ae',
    }],
    scholarships: [
      {
        id: 'sch-ud-excellence',
        name: 'University of Dubai Merit Scholarship',
        awardAmount: 20000,
        currency: 'AED',
        deadline: '2026-08-15',
        eligibility: 'High-achieving international applicants with GPA 3.5+.',
        requirements: 'Admission application and scholarship essay.',
        sourceUrl: 'https://www.ud.ac.ae',
        courseSlug: 'ud-mba',
      },
    ],
  },
  // ─── Italy ─────────────────────────────────────────────────────────────────
  {
    name: 'Politecnico di Milano',
    slug: 'politecnico-di-milano',
    countryCode: 'IT',
    worldRanking: 111,
    tuitionMin: 4000,
    tuitionMax: 12000,
    acceptanceRate: 40,
    description: 'Italy\'s top technical university for engineering, architecture, and design with English-taught masters.',
    website: 'https://www.polimi.it',
    popularPrograms: ['Engineering', 'Architecture', 'Design', 'Computer Science'],
    courses: [
      {
        name: 'MSc Computer Science and Engineering',
        slug: 'polimi-msc-cse',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 3894,
        currency: 'EUR',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'CS or engineering bachelor\'s. IELTS 6.0.',
        description: 'English-taught computer science masters at Politecnico di Milano.',
        sourceUrl: 'https://www.polimi.it',
      },
      {
        name: 'MSc Management Engineering',
        slug: 'polimi-msc-management-engineering',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 3894,
        currency: 'EUR',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'Engineering or economics bachelor\'s. IELTS 6.0.',
        description: 'Interdisciplinary management and engineering programme.',
        sourceUrl: 'https://www.polimi.it',
      },
    ],
    scholarships: [
      {
        id: 'sch-polimi-gold',
        name: 'Polimi Gold Medal Scholarship',
        awardAmount: 10000,
        currency: 'EUR',
        deadline: '2026-05-30',
        eligibility: 'Outstanding international MSc applicants.',
        requirements: 'Merit-based selection with admission application.',
        sourceUrl: 'https://www.polimi.it',
      },
    ],
  },
  {
    name: 'University of Bologna',
    slug: 'university-of-bologna',
    countryCode: 'IT',
    worldRanking: 133,
    tuitionMin: 3000,
    tuitionMax: 8000,
    acceptanceRate: 55,
    description: 'Europe\'s oldest university with affordable tuition and growing English-taught programmes.',
    website: 'https://www.unibo.it',
    popularPrograms: ['Economics', 'Engineering', 'Law', 'Data Science'],
    courses: [
      {
        name: 'MSc in Artificial Intelligence',
        slug: 'unibo-msc-ai',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 3500,
        currency: 'EUR',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'CS or related bachelor\'s. IELTS 6.0.',
        description: 'AI masters combining machine learning, NLP, and robotics.',
        sourceUrl: 'https://www.unibo.it',
      },
    ],
    scholarships: [
      {
        id: 'sch-unibo-study-grant',
        name: 'Unibo Action 1 Study Grant',
        awardAmount: 11000,
        currency: 'EUR',
        deadline: '2026-04-30',
        eligibility: 'International students with strong academic merit.',
        requirements: 'Online scholarship application with admission.',
        sourceUrl: 'https://www.unibo.it',
      },
    ],
  },
  // ─── Japan ─────────────────────────────────────────────────────────────────
  {
    name: 'University of Tokyo',
    slug: 'university-of-tokyo',
    countryCode: 'JP',
    worldRanking: 28,
    tuitionMin: 500000,
    tuitionMax: 1500000,
    acceptanceRate: 20,
    description: 'Japan\'s most prestigious university with PEAK English programmes and MEXT scholarship pathways.',
    website: 'https://www.u-tokyo.ac.jp',
    popularPrograms: ['Engineering', 'Economics', 'Computer Science', 'International Relations'],
    courses: [
      {
        name: 'Bachelor of Arts in International Liberal Studies (PEAK)',
        slug: 'utokyo-peak-balis',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '4 years',
        tuition: 535800,
        currency: 'JPY',
        intakePeriods: [IntakePeriod.APRIL],
        eligibility: 'Strong high school record. IELTS 7.0+. No Japanese required.',
        description: 'All-English liberal arts undergraduate at University of Tokyo.',
        sourceUrl: 'https://www.u-tokyo.ac.jp',
      },
      {
        name: 'MSc in Information Science and Technology',
        slug: 'utokyo-msc-ist',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 535800,
        currency: 'JPY',
        intakePeriods: [IntakePeriod.APRIL, IntakePeriod.SEPTEMBER],
        eligibility: 'CS bachelor\'s. English proficiency required.',
        description: 'Graduate programme in information science at UTokyo.',
        sourceUrl: 'https://www.u-tokyo.ac.jp',
      },
    ],
    scholarships: [
      {
        id: 'sch-mext-japan',
        name: 'MEXT (Monbukagakusho) Scholarship',
        awardAmount: 1500000,
        currency: 'JPY',
        deadline: '2026-09-01',
        eligibility: 'International students applying to Japanese universities.',
        requirements: 'Embassy recommendation or university recommendation track.',
        sourceUrl: 'https://www.studyinjapan.go.jp',
      },
    ],
  },
  {
    name: 'Kyoto University',
    slug: 'kyoto-university',
    countryCode: 'JP',
    worldRanking: 46,
    tuitionMin: 500000,
    tuitionMax: 1200000,
    acceptanceRate: 25,
    description: 'Top national university known for research excellence in science, medicine, and humanities.',
    website: 'https://www.kyoto-u.ac.jp',
    popularPrograms: ['Engineering', 'Medicine', 'Environmental Science', 'Economics'],
    courses: [
      {
        name: 'MSc in Civil and Earth Resources Engineering',
        slug: 'kyoto-msc-civil-engineering',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 535800,
        currency: 'JPY',
        intakePeriods: [IntakePeriod.APRIL],
        eligibility: 'Engineering bachelor\'s. IELTS 6.5.',
        description: 'English-track civil engineering masters at Kyoto University.',
        sourceUrl: 'https://www.kyoto-u.ac.jp',
      },
    ],
    scholarships: [
      {
        id: 'sch-kyoto-international',
        name: 'Kyoto University International Scholarship',
        awardAmount: 800000,
        currency: 'JPY',
        deadline: '2026-03-15',
        eligibility: 'Self-funded international graduate students with outstanding records.',
        requirements: 'Graduate admission application.',
        sourceUrl: 'https://www.kyoto-u.ac.jp',
      },
    ],
  },
  // ─── South Korea ───────────────────────────────────────────────────────────
  {
    name: 'Seoul National University',
    slug: 'seoul-national-university',
    countryCode: 'KR',
    worldRanking: 29,
    tuitionMin: 4000000,
    tuitionMax: 12000000,
    acceptanceRate: 22,
    description: 'South Korea\'s flagship university with GKS scholarships and strong STEM programmes.',
    website: 'https://www.snu.ac.kr',
    popularPrograms: ['Engineering', 'Business', 'Computer Science', 'International Studies'],
    courses: [
      {
        name: 'MSc in Computer Science and Engineering',
        slug: 'snu-msc-cse',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 6500000,
        currency: 'KRW',
        intakePeriods: [IntakePeriod.MARCH, IntakePeriod.SEPTEMBER],
        eligibility: 'CS bachelor\'s. IELTS 6.5 or TOEFL 80.',
        description: 'Graduate computer science at Seoul National University.',
        sourceUrl: 'https://www.snu.ac.kr',
      },
      {
        name: 'MBA',
        slug: 'snu-mba',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 12000000,
        currency: 'KRW',
        intakePeriods: [IntakePeriod.MARCH],
        eligibility: 'Bachelor\'s + work experience. GMAT/GRE. IELTS 7.0.',
        description: 'SNU Business School MBA programme.',
        sourceUrl: 'https://www.snu.ac.kr',
      },
    ],
    scholarships: [
      {
        id: 'sch-gks-korea',
        name: 'Global Korea Scholarship (GKS)',
        awardAmount: 10000000,
        currency: 'KRW',
        deadline: '2026-03-01',
        eligibility: 'International students pursuing degree programmes in Korea.',
        requirements: 'GKS application through Korean embassy or university.',
        sourceUrl: 'https://www.studyinkorea.go.kr',
      },
    ],
  },
  {
    name: 'KAIST',
    slug: 'kaist',
    countryCode: 'KR',
    worldRanking: 53,
    tuitionMin: 3000000,
    tuitionMax: 8000000,
    acceptanceRate: 18,
    description: 'Korea Advanced Institute of Science and Technology — Asia\'s MIT for engineering and technology.',
    website: 'https://www.kaist.ac.kr',
    popularPrograms: ['Computer Science', 'Electrical Engineering', 'Robotics', 'Biotech'],
    courses: [
      {
        name: 'MSc in Computer Science',
        slug: 'kaist-msc-cs',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 5000000,
        currency: 'KRW',
        intakePeriods: [IntakePeriod.MARCH, IntakePeriod.SEPTEMBER],
        eligibility: 'CS bachelor\'s with strong GPA. IELTS 6.5.',
        description: 'Research-focused CS masters at KAIST School of Computing.',
        sourceUrl: 'https://www.kaist.ac.kr',
      },
    ],
    scholarships: [
      {
        id: 'sch-kaist-international',
        name: 'KAIST International Student Scholarship',
        awardAmount: 5000000,
        currency: 'KRW',
        deadline: '2026-04-15',
        eligibility: 'Outstanding international graduate applicants.',
        requirements: 'Automatic consideration with graduate admission.',
        sourceUrl: 'https://www.kaist.ac.kr',
      },
    ],
  },
  // ─── Malaysia ──────────────────────────────────────────────────────────────
  {
    name: 'University of Malaya',
    slug: 'university-of-malaya',
    countryCode: 'MY',
    worldRanking: 65,
    tuitionMin: 20000,
    tuitionMax: 50000,
    acceptanceRate: 50,
    description: 'Malaysia\'s oldest and highest-ranked university with affordable fees and multicultural campus.',
    website: 'https://www.um.edu.my',
    popularPrograms: ['Engineering', 'Medicine', 'Business', 'Computer Science'],
    courses: [
      {
        name: 'BSc in Computer Science',
        slug: 'um-bsc-computer-science',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '3 years',
        tuition: 35000,
        currency: 'MYR',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'STPM/A-levels with mathematics. IELTS 5.5.',
        description: 'Undergraduate computer science at University of Malaya.',
        sourceUrl: 'https://www.um.edu.my',
      },
      {
        name: 'MSc in Data Science',
        slug: 'um-msc-data-science',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '1.5 years',
        tuition: 42000,
        currency: 'MYR',
        intakePeriods: [IntakePeriod.SEPTEMBER, IntakePeriod.FEBRUARY],
        eligibility: 'Quantitative bachelor\'s. IELTS 6.0.',
        description: 'Data science masters combining statistics, ML, and analytics.',
        sourceUrl: 'https://www.um.edu.my',
      },
    ],
    scholarships: [
      {
        id: 'sch-um-international',
        name: 'UM International Student Scholarship',
        awardAmount: 15000,
        currency: 'MYR',
        deadline: '2026-06-30',
        eligibility: 'International students with academic excellence.',
        requirements: 'Admission application and scholarship form.',
        sourceUrl: 'https://www.um.edu.my',
      },
    ],
  },
  {
    name: 'Monash University Malaysia',
    slug: 'monash-university-malaysia',
    countryCode: 'MY',
    worldRanking: 42,
    tuitionMin: 40000,
    tuitionMax: 90000,
    acceptanceRate: 60,
    description: 'Australian branch campus in Malaysia offering globally recognised degrees at lower cost.',
    website: 'https://www.monash.edu.my',
    popularPrograms: ['Engineering', 'Business', 'Medicine', 'IT'],
    courses: [
      {
        name: 'Bachelor of Computer Science',
        slug: 'monash-my-bcs',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '3 years',
        tuition: 55000,
        currency: 'MYR',
        intakePeriods: [IntakePeriod.FEBRUARY, IntakePeriod.SEPTEMBER],
        eligibility: 'A-levels or equivalent. IELTS 6.5.',
        description: 'Monash CS degree awarded at Malaysia campus.',
        sourceUrl: 'https://www.monash.edu.my',
      },
    ],
    scholarships: [
      {
        id: 'sch-monash-my-merit',
        name: 'Monash Malaysia High Achiever Scholarship',
        awardAmount: 25000,
        currency: 'MYR',
        deadline: '2026-05-15',
        eligibility: 'High-achieving international undergraduate applicants.',
        requirements: 'Automatic merit assessment with application.',
        sourceUrl: 'https://www.monash.edu.my',
      },
    ],
  },
  // ─── Sweden ────────────────────────────────────────────────────────────────
  {
    name: 'KTH Royal Institute of Technology',
    slug: 'kth-royal-institute-technology',
    countryCode: 'SE',
    worldRanking: 73,
    tuitionMin: 150000,
    tuitionMax: 350000,
    acceptanceRate: 45,
    description: 'Sweden\'s largest technical university with innovation focus and English-taught masters.',
    website: 'https://www.kth.se',
    popularPrograms: ['Computer Science', 'Electrical Engineering', 'Sustainability', 'Architecture'],
    courses: [
      {
        name: 'MSc Computer Science',
        slug: 'kth-msc-cs',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 310000,
        currency: 'SEK',
        intakePeriods: [IntakePeriod.AUGUST],
        eligibility: 'CS bachelor\'s. IELTS 6.5.',
        description: 'English-taught computer science masters at KTH.',
        sourceUrl: 'https://www.kth.se',
      },
      {
        name: 'MSc Sustainable Energy Engineering',
        slug: 'kth-msc-sustainable-energy',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 310000,
        currency: 'SEK',
        intakePeriods: [IntakePeriod.AUGUST],
        eligibility: 'Engineering bachelor\'s. IELTS 6.5.',
        description: 'Sustainability and energy systems masters programme.',
        sourceUrl: 'https://www.kth.se',
      },
    ],
    scholarships: [
      {
        id: 'sch-kth-india',
        name: 'KTH India Scholarship',
        awardAmount: 310000,
        currency: 'SEK',
        deadline: '2026-01-15',
        eligibility: 'Fee-paying Indian students admitted to KTH masters.',
        requirements: 'Automatic consideration with masters application.',
        sourceUrl: 'https://www.kth.se',
      },
    ],
  },
  {
    name: 'Lund University',
    slug: 'lund-university',
    countryCode: 'SE',
    worldRanking: 85,
    tuitionMin: 100000,
    tuitionMax: 300000,
    acceptanceRate: 50,
    description: 'One of Scandinavia\'s oldest universities with strong research and international student community.',
    website: 'https://www.lu.se',
    popularPrograms: ['Engineering', 'Economics', 'International Business', 'Data Analytics'],
    courses: [
      {
        name: 'MSc in Data Analytics and Business Economics',
        slug: 'lund-msc-data-analytics',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 265000,
        currency: 'SEK',
        intakePeriods: [IntakePeriod.AUGUST],
        eligibility: 'Economics or quantitative bachelor\'s. IELTS 6.5.',
        description: 'Interdisciplinary data analytics and business programme.',
        sourceUrl: 'https://www.lu.se',
      },
    ],
    scholarships: [
      {
        id: 'sch-lund-global',
        name: 'Lund University Global Scholarship',
        awardAmount: 200000,
        currency: 'SEK',
        deadline: '2026-02-15',
        eligibility: 'Top academic international masters applicants.',
        requirements: 'Merit-based selection during admission.',
        sourceUrl: 'https://www.lu.se',
      },
    ],
  },
  // ─── Spain ─────────────────────────────────────────────────────────────────
  {
    name: 'University of Barcelona',
    slug: 'university-of-barcelona',
    countryCode: 'ES',
    worldRanking: 164,
    tuitionMin: 2000,
    tuitionMax: 8000,
    acceptanceRate: 55,
    description: 'Leading Spanish public university in vibrant Barcelona with affordable EU tuition.',
    website: 'https://www.ub.edu',
    popularPrograms: ['Economics', 'Biology', 'Computer Science', 'Tourism'],
    courses: [
      {
        name: 'MSc in Data Science',
        slug: 'ub-msc-data-science',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '1 year',
        tuition: 4500,
        currency: 'EUR',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'Quantitative bachelor\'s. IELTS 6.5 or Spanish B2.',
        description: 'Data science masters at University of Barcelona.',
        sourceUrl: 'https://www.ub.edu',
      },
      {
        name: 'BSc in Computer Engineering',
        slug: 'ub-bsc-computer-engineering',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '4 years',
        tuition: 2500,
        currency: 'EUR',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'Baccalaureate with mathematics. Spanish or English track.',
        description: 'Computer engineering undergraduate at UB.',
        sourceUrl: 'https://www.ub.edu',
      },
    ],
    scholarships: [
      {
        id: 'sch-ub-mobility',
        name: 'UB International Mobility Grant',
        awardAmount: 5000,
        currency: 'EUR',
        deadline: '2026-05-31',
        eligibility: 'International students with financial need.',
        requirements: 'Admission and grant application.',
        sourceUrl: 'https://www.ub.edu',
      },
    ],
  },
  {
    name: 'IE University',
    slug: 'ie-university',
    countryCode: 'ES',
    worldRanking: 0,
    tuitionMin: 25000,
    tuitionMax: 45000,
    acceptanceRate: 35,
    description: 'Private Spanish university renowned for business, law, and technology with global outlook.',
    website: 'https://www.ie.edu',
    popularPrograms: ['MBA', 'Business Analytics', 'Law', 'Architecture'],
    courses: [
      {
        name: 'Master in Business Analytics & Big Data',
        slug: 'ie-mba-big-data',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '11 months',
        tuition: 42000,
        currency: 'EUR',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'Quantitative bachelor\'s. IELTS 7.0. GMAT optional.',
        description: 'Intensive business analytics masters at IE Madrid.',
        sourceUrl: 'https://www.ie.edu',
      },
    ],
    scholarships: [
      {
        id: 'sch-ie-talent',
        name: 'IE Talent Scholarship',
        awardAmount: 15000,
        currency: 'EUR',
        deadline: '2026-06-15',
        eligibility: 'Outstanding international masters applicants.',
        requirements: 'Merit-based award with programme application.',
        sourceUrl: 'https://www.ie.edu',
      },
    ],
  },
  // ─── Finland ───────────────────────────────────────────────────────────────
  {
    name: 'University of Helsinki',
    slug: 'university-of-helsinki',
    countryCode: 'FI',
    worldRanking: 107,
    tuitionMin: 13000,
    tuitionMax: 18000,
    acceptanceRate: 48,
    description: 'Finland\'s oldest and largest university with English-taught masters and high research output.',
    website: 'https://www.helsinki.fi',
    popularPrograms: ['Computer Science', 'Environmental Science', 'Medicine', 'Education'],
    courses: [
      {
        name: 'MSc in Computer Science',
        slug: 'helsinki-msc-cs',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 15000,
        currency: 'EUR',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'CS bachelor\'s. IELTS 6.5.',
        description: 'English-taught computer science masters at University of Helsinki.',
        sourceUrl: 'https://www.helsinki.fi',
      },
      {
        name: 'MSc in Data Science',
        slug: 'helsinki-msc-data-science',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 15000,
        currency: 'EUR',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'Quantitative bachelor\'s. IELTS 6.5.',
        description: 'Interdisciplinary data science programme.',
        sourceUrl: 'https://www.helsinki.fi',
      },
    ],
    scholarships: [
      {
        id: 'sch-helsinki-merit',
        name: 'University of Helsinki Scholarship',
        awardAmount: 10000,
        currency: 'EUR',
        deadline: '2026-01-31',
        eligibility: 'Non-EU/EEA students with excellent academic records.',
        requirements: 'Automatic consideration with masters application.',
        sourceUrl: 'https://www.helsinki.fi',
      },
    ],
  },
  {
    name: 'Aalto University',
    slug: 'aalto-university',
    countryCode: 'FI',
    worldRanking: 109,
    tuitionMin: 12000,
    tuitionMax: 18000,
    acceptanceRate: 42,
    description: 'Finnish multidisciplinary university combining technology, business, and design.',
    website: 'https://www.aalto.fi',
    popularPrograms: ['Computer Science', 'Design', 'Business', 'Engineering'],
    courses: [
      {
        name: 'MSc in Computer, Communication and Information Sciences',
        slug: 'aalto-msc-ccis',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 15000,
        currency: 'EUR',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'CS or EE bachelor\'s. IELTS 6.5.',
        description: 'CCIS masters with specialisations in ML, security, and networks.',
        sourceUrl: 'https://www.aalto.fi',
      },
    ],
    scholarships: [
      {
        id: 'sch-aalto-excellence',
        name: 'Aalto University Excellence Scholarship',
        awardAmount: 12000,
        currency: 'EUR',
        deadline: '2026-01-15',
        eligibility: 'Non-EU masters applicants with outstanding merit.',
        requirements: 'Merit-based tuition waiver with admission.',
        sourceUrl: 'https://www.aalto.fi',
      },
    ],
  },
  // ─── Additional universities for existing destinations ─────────────────────
  {
    name: 'McGill University',
    slug: 'mcgill-university',
    countryCode: 'CA',
    worldRanking: 30,
    tuitionMin: 22000,
    tuitionMax: 55000,
    acceptanceRate: 46,
    description: 'Canada\'s top-ranked university in Montreal with global reputation in medicine, law, and engineering.',
    website: 'https://www.mcgill.ca',
    popularPrograms: ['Medicine', 'Engineering', 'Computer Science', 'Management'],
    courses: [
      {
        name: 'BSc in Computer Science',
        slug: 'mcgill-bsc-cs',
        degreeLevel: DegreeLevel.BACHELORS,
        duration: '3 years',
        tuition: 48000,
        currency: 'CAD',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'Strong high school grades in math/science. IELTS 6.5.',
        description: 'Computer science undergraduate at McGill Faculty of Science.',
        sourceUrl: 'https://www.mcgill.ca',
      },
    ],
    scholarships: [
      {
        id: 'sch-mcgill-entrance',
        name: 'McGill Entrance Scholarship',
        awardAmount: 12000,
        currency: 'CAD',
        deadline: '2026-03-01',
        eligibility: 'High-achieving international undergraduate applicants.',
        requirements: 'Automatic consideration with admission application.',
        sourceUrl: 'https://www.mcgill.ca',
      },
    ],
  },
  {
    name: 'RWTH Aachen University',
    slug: 'rwth-aachen-university',
    countryCode: 'DE',
    worldRanking: 99,
    tuitionMin: 0,
    tuitionMax: 5000,
    acceptanceRate: 50,
    description: 'Germany\'s largest technical university with industry partnerships and low tuition fees.',
    website: 'https://www.rwth-aachen.de',
    popularPrograms: ['Mechanical Engineering', 'Computer Science', 'Electrical Engineering', 'Physics'],
    courses: [
      {
        name: 'MSc in Computer Science',
        slug: 'rwth-msc-cs',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '2 years',
        tuition: 0,
        currency: 'EUR',
        intakePeriods: [IntakePeriod.OCTOBER, IntakePeriod.APRIL],
        eligibility: 'CS bachelor\'s. IELTS 6.5 or German B2.',
        description: 'English/German CS masters at RWTH Aachen.',
        sourceUrl: 'https://www.rwth-aachen.de',
      },
    ],
    scholarships: [
      {
        id: 'sch-daad-germany',
        name: 'DAAD Scholarship (Germany)',
        awardAmount: 12000,
        currency: 'EUR',
        deadline: '2026-10-15',
        eligibility: 'International students pursuing graduate study in Germany.',
        requirements: 'DAAD online application with university admission.',
        sourceUrl: 'https://www.daad.de',
      },
    ],
  },
  {
    name: 'University College Dublin',
    slug: 'university-college-dublin',
    countryCode: 'IE',
    worldRanking: 126,
    tuitionMin: 18000,
    tuitionMax: 32000,
    acceptanceRate: 52,
    description: 'Ireland\'s largest university with strong business, computing, and pharma programmes.',
    website: 'https://www.ucd.ie',
    popularPrograms: ['Business', 'Computer Science', 'Pharmacy', 'Veterinary Science'],
    courses: [
      {
        name: 'MSc in Computer Science (Conversion)',
        slug: 'ucd-msc-cs-conversion',
        degreeLevel: DegreeLevel.MASTERS,
        duration: '1.5 years',
        tuition: 26000,
        currency: 'EUR',
        intakePeriods: [IntakePeriod.SEPTEMBER],
        eligibility: 'Non-CS bachelor\'s with aptitude for computing. IELTS 6.5.',
        description: 'Conversion masters for career changers into computer science.',
        sourceUrl: 'https://www.ucd.ie',
      },
    ],
    scholarships: [
      {
        id: 'sch-ucd-global',
        name: 'UCD Global Excellence Scholarship',
        awardAmount: 10000,
        currency: 'EUR',
        deadline: '2026-04-30',
        eligibility: 'International students with first-class academic records.',
        requirements: 'Automatic merit review with admission.',
        sourceUrl: 'https://www.ucd.ie',
      },
    ],
  },
];
