export const DOCUMENT_CHECKLISTS = {
  US: {
    label: 'USA',
    flag: '🇺🇸',
    undergraduate: [
      '10th & 12th mark sheets',
      'SAT / ACT scores (if required)',
      'English proficiency (IELTS / TOEFL / Duolingo)',
      'Statement of Purpose / Personal Essay',
      '2–3 Letters of Recommendation',
      'Resume / CV',
      'Financial documents & bank statements',
      'Passport copy',
      'F-1 visa application (I-20, DS-160, SEVIS fee)',
    ],
    postgraduate: [
      'Bachelor\'s degree transcripts & certificates',
      'English proficiency (IELTS / TOEFL)',
      'GRE / GMAT scores (program-dependent)',
      'Statement of Purpose',
      '3 Letters of Recommendation',
      'Resume / CV with projects & work experience',
      'Financial proof for I-20',
      'Passport copy',
      'F-1 visa documents',
    ],
  },
  GB: {
    label: 'United Kingdom',
    flag: '🇬🇧',
    undergraduate: [
      '10th & 12th mark sheets',
      'English proficiency (IELTS UKVI / PTE)',
      'Personal Statement (UCAS)',
      'Academic Reference',
      'Passport copy',
      'CAS letter (post-offer)',
      'Financial evidence for Student visa',
      'TB test certificate (if applicable)',
    ],
    postgraduate: [
      'Bachelor\'s transcripts & degree certificate',
      'English proficiency (IELTS UKVI / PTE)',
      'Personal Statement',
      '2 Academic References',
      'Resume / CV',
      'Passport copy',
      'CAS letter (post-offer)',
      'Financial evidence (£ requirements)',
      'ATAS certificate (if required for certain courses)',
    ],
  },
  AU: {
    label: 'Australia',
    flag: '🇦🇺',
    undergraduate: [
      '10th & 12th mark sheets',
      'English proficiency (IELTS / PTE / TOEFL)',
      'Statement of Purpose',
      'Academic references',
      'Passport copy',
      'CoE (Confirmation of Enrolment) post-offer',
      'Genuine Student (GS) statement',
      'Financial capacity evidence',
      'OSHC health insurance',
      'Student visa (subclass 500) documents',
    ],
    postgraduate: [
      'Bachelor\'s degree transcripts',
      'English proficiency scores',
      'Statement of Purpose',
      '2 References (academic / professional)',
      'Resume / CV',
      'Passport copy',
      'CoE post-offer',
      'Genuine Student (GS) statement',
      'Financial evidence',
      'OSHC health insurance',
    ],
  },
} as const;
